//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/richardlalancette/youidev/ImGui.NET/src/ImGui.NET.SampleProgram/youi.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="youiParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IyouiListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="youiParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] youiParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="youiParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] youiParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="youiParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] youiParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="youiParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] youiParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="youiParser.control_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControl_arguments([NotNull] youiParser.Control_argumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="youiParser.control_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControl_arguments([NotNull] youiParser.Control_argumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="youiParser.screen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScreen([NotNull] youiParser.ScreenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="youiParser.screen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScreen([NotNull] youiParser.ScreenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="youiParser.button"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterButton([NotNull] youiParser.ButtonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="youiParser.button"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitButton([NotNull] youiParser.ButtonContext context);
}
